/*
 * Copyright (c) 2020 The ZMK Contributors
 * Copyright (c) 2026 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 *
 * Adapted from petejohanson/zmk's feat/pointers-move-scroll-ptp,
 * commit 455ad3eafaccf6f85be23c45fae6d74f113e098c.
 */

#pragma once

#include <zephyr/usb/class/usb_hid.h>
#include <zephyr/sys/util_macro.h>
#include <dt-bindings/zmk/hid_usage.h>
#include <dt-bindings/zmk/hid_usage_pages.h>
#include <zmk/ptp/transport.h>

#define PTP_DATA 0x02    /* Data, Variable, Absolute */
#define PTP_PADDING 0x03 /* Constant, Variable, Absolute */
#define PTP_PHYSICAL_MAX16(v)                                                                      \
    HID_ITEM(HID_ITEM_TAG_PHYSICAL_MAX, HID_ITEM_TYPE_GLOBAL, 2), (v & 0xff), ((v >> 8) & 0xff)
#define PTP_PHYSICAL_MIN8(v) HID_ITEM(HID_ITEM_TAG_PHYSICAL_MIN, HID_ITEM_TYPE_GLOBAL, 1), v
#define PTP_PHYSICAL_MAX8(v) HID_ITEM(HID_ITEM_TAG_PHYSICAL_MAX, HID_ITEM_TYPE_GLOBAL, 1), v
#define PTP_PHYSICAL_MAX32(a, b, c, d)                                                             \
    HID_ITEM(HID_ITEM_TAG_PHYSICAL_MAX, HID_ITEM_TYPE_GLOBAL, 3), a, b, c, d
#define PTP_UNIT(v) HID_ITEM(HID_ITEM_TAG_UNIT, HID_ITEM_TYPE_GLOBAL, 1), v
#define PTP_EXPONENT(v) HID_ITEM(HID_ITEM_TAG_UNIT_EXPONENT, HID_ITEM_TYPE_GLOBAL, 1), v
#define PTP_UNIT_SECONDS HID_ITEM(HID_ITEM_TAG_UNIT, HID_ITEM_TYPE_GLOBAL, 2), 0x01, 0x10
#define PTP_REPORT_COUNT256 HID_ITEM(HID_ITEM_TAG_REPORT_COUNT, HID_ITEM_TYPE_GLOBAL, 2), 0x00, 0x01

#define PTP_FINGER_DESC(n, _)                                                                      \
    HID_USAGE_PAGE(HID_USAGE_DIGITIZERS), HID_USAGE(HID_USAGE_DIGITIZERS_FINGER),                  \
        HID_COLLECTION(HID_COLLECTION_LOGICAL), PTP_UNIT(0), PTP_EXPONENT(0),                      \
        PTP_PHYSICAL_MIN8(0), PTP_PHYSICAL_MAX8(0), HID_LOGICAL_MIN8(0), HID_LOGICAL_MAX8(1),      \
        HID_USAGE(HID_USAGE_DIGITIZERS_TOUCH_VALID), HID_USAGE(HID_USAGE_DIGITIZERS_TIP_SWITCH),   \
        HID_REPORT_COUNT(2), HID_REPORT_SIZE(1), HID_INPUT(PTP_DATA),                              \
        HID_USAGE(HID_USAGE_DIGITIZERS_CONTACT_IDENTIFIER),                                        \
        HID_LOGICAL_MAX8(CONFIG_ZMK_TRACKPAD_FINGERS - 1), HID_REPORT_COUNT(1),                    \
        HID_REPORT_SIZE(4), HID_INPUT(PTP_DATA), HID_REPORT_SIZE(2), HID_INPUT(PTP_PADDING),       \
        HID_USAGE_PAGE(HID_USAGE_GD), HID_USAGE(HID_USAGE_GD_X),                                   \
        HID_LOGICAL_MAX16(CONFIG_ZMK_TRACKPAD_LOGICAL_X & 0xff,                                    \
                          CONFIG_ZMK_TRACKPAD_LOGICAL_X >> 8),                                     \
        PTP_PHYSICAL_MIN8(0), PTP_PHYSICAL_MAX16(CONFIG_ZMK_TRACKPAD_PHYSICAL_X), PTP_UNIT(0x11),  \
        PTP_EXPONENT(0x0e), HID_REPORT_SIZE(16), HID_INPUT(PTP_DATA), HID_USAGE(HID_USAGE_GD_Y),   \
        HID_LOGICAL_MAX16(CONFIG_ZMK_TRACKPAD_LOGICAL_Y & 0xff,                                    \
                          CONFIG_ZMK_TRACKPAD_LOGICAL_Y >> 8),                                     \
        PTP_PHYSICAL_MAX16(CONFIG_ZMK_TRACKPAD_PHYSICAL_Y), HID_INPUT(PTP_DATA),                   \
        HID_END_COLLECTION,

static const uint8_t zmk_ptp_hid_report_desc[] = {
    HID_USAGE_PAGE(HID_USAGE_DIGITIZERS),
    HID_USAGE(HID_USAGE_DIGITIZERS_TOUCH_PAD),
    HID_COLLECTION(HID_COLLECTION_APPLICATION),
    HID_REPORT_ID(ZMK_PTP_REPORT_ID_INPUT),
    LISTIFY(CONFIG_ZMK_TRACKPAD_FINGERS, PTP_FINGER_DESC, ())

        HID_USAGE_PAGE(HID_USAGE_DIGITIZERS),
    HID_USAGE(HID_USAGE_DIGITIZERS_SCAN_TIME),
    HID_LOGICAL_MIN8(0),
    HID_LOGICAL_MAX32(0xff, 0xff, 0, 0),
    PTP_PHYSICAL_MIN8(0),
    PTP_PHYSICAL_MAX32(0xff, 0xff, 0, 0),
    PTP_UNIT_SECONDS,
    PTP_EXPONENT(0x0c),
    HID_REPORT_SIZE(16),
    HID_REPORT_COUNT(1),
    HID_INPUT(PTP_DATA),

    /* Do not leak scan-time units/ranges into counts, buttons or features. */
    PTP_UNIT(0),
    PTP_EXPONENT(0),
    PTP_PHYSICAL_MIN8(0),
    PTP_PHYSICAL_MAX8(0),
    HID_USAGE(HID_USAGE_DIGITIZERS_CONTACT_COUNT),
    HID_LOGICAL_MAX8(CONFIG_ZMK_TRACKPAD_FINGERS),
    HID_REPORT_SIZE(4),
    HID_INPUT(PTP_DATA),
    HID_USAGE_PAGE(HID_USAGE_BUTTON),
    HID_USAGE_MIN8(1),
    HID_USAGE_MAX8(3),
    HID_LOGICAL_MAX8(1),
    HID_REPORT_SIZE(1),
    HID_REPORT_COUNT(3),
    HID_INPUT(PTP_DATA),
    HID_REPORT_COUNT(1),
    HID_INPUT(PTP_PADDING),

    HID_USAGE_PAGE(HID_USAGE_DIGITIZERS),
    HID_REPORT_ID(ZMK_PTP_REPORT_ID_CAPABILITIES),
    HID_USAGE(HID_USAGE_DIGITIZERS_CONTACT_COUNT_MAXIMUM),
    HID_LOGICAL_MAX8(CONFIG_ZMK_TRACKPAD_FINGERS),
    HID_REPORT_SIZE(4),
    HID_REPORT_COUNT(1),
    HID_FEATURE(PTP_DATA),
    HID_USAGE(HID_USAGE_DIGITIZERS_PAD_TYPE),
    HID_LOGICAL_MAX8(2),
    HID_FEATURE(PTP_DATA),

    /* Uncertified status blob, not a claim of Windows certification. */
    HID_ITEM(HID_ITEM_TAG_USAGE_PAGE, HID_ITEM_TYPE_GLOBAL, 2),
    0x00,
    0xff,
    HID_REPORT_ID(ZMK_PTP_REPORT_ID_CERTIFICATION),
    HID_USAGE(0xc5),
    HID_LOGICAL_MAX16(0xff, 0),
    HID_REPORT_SIZE(8),
    PTP_REPORT_COUNT256,
    HID_FEATURE(PTP_DATA),
    HID_END_COLLECTION,

    HID_USAGE_PAGE(HID_USAGE_DIGITIZERS),
    HID_USAGE(HID_USAGE_DIGITIZERS_DEVICE_CONFIGURATION),
    HID_COLLECTION(HID_COLLECTION_APPLICATION),
    HID_REPORT_ID(ZMK_PTP_REPORT_ID_MODE),
    HID_USAGE(HID_USAGE_DIGITIZERS_FINGER),
    HID_COLLECTION(HID_COLLECTION_LOGICAL),
    HID_USAGE(HID_USAGE_DIGITIZERS_DEVICE_MODE),
    HID_LOGICAL_MAX8(ZMK_PTP_MODE_TOUCHPAD),
    HID_REPORT_SIZE(8),
    HID_REPORT_COUNT(1),
    HID_FEATURE(PTP_DATA),
    HID_END_COLLECTION,

    HID_REPORT_ID(ZMK_PTP_REPORT_ID_SELECTIVE),
    HID_USAGE(HID_USAGE_DIGITIZERS_FINGER),
    HID_COLLECTION(HID_COLLECTION_LOGICAL),
    HID_USAGE(HID_USAGE_DIGITIZERS_SURFACE_SWITCH),
    HID_USAGE(HID_USAGE_DIGITIZERS_BUTTON_SWITCH),
    HID_LOGICAL_MAX8(1),
    HID_REPORT_SIZE(1),
    HID_REPORT_COUNT(2),
    HID_FEATURE(PTP_DATA),
    HID_REPORT_COUNT(6),
    HID_FEATURE(PTP_PADDING),
    HID_END_COLLECTION,
    HID_END_COLLECTION,
};
